spring:
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    properties:
      hibernate:
#        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  profiles:
    active: aws, email
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      fail-on-empty-beans: false

server:
  error:
    include-stacktrace: on_param # 응답에 예외 정보 간략하게만 찍기
    include-exception: true

logging:
  level:
    org.hibernate.SQL: debug